### ISSUE TITLE
About 8 bit quantization

### ISSUE THREAD

**Issue by infrontofme** [venturezhao/XJTU-Tripler#3]
Hi, Thanks for sharing your work!

I wonder which article does your quantization method refers to?

Do you plan to make the quantization code public?

Thanks:)

**Comment by venturezhao** [comment]
Hi~ Thanks for your reply~
Our quantization method follows the NVIDIA conventional 8-bit quantization method, with symmetric Max/Min value, 2^N scalar.
Since the quantization algorithm is our neighbor team's work, while I focused on the computing architecture, I have no idea about whether they will public their quantization method...
