### ISSUE TITLE
About HiPU

### ISSUE THREAD

**Issue by francis2tm** [venturezhao/XJTU-Tripler#5]
Hello,
Is there any paper or documentation regarding the HiPU? I was hoping to get a more documented insight!

Thanks in advance

**Comment by venturezhao** [comment]
> Hello,
> Is there any paper or documentation regarding the HiPU? I was hoping to get a more documented insight!
> 
> Thanks in advance

Since this work is mostly project oriented, with little innovation compared with the SOTA design in academic,  we have not published this work yet so far. Sorry...

**Comment by francis2tm** [comment]
@venturezhao  Thank you!
And is HiPU dependent on Xilinx fpgas or can it be tested and deployed in another vendor's fpga? Like lattice?
Probably only some modifications are required.

Thanks

**Comment by venturezhao** [comment]
> @venturezhao Thank you!
> And is HiPU dependent on Xilinx fpgas or can it be tested and deployed in another vendor's fpga? Like lattice?
> Probably only some modifications are required.
> 
> Thanks

At this time, the HiPU is specially optimized for Xilinx ultra-scale FPGAs, since the DSP(DSP48e2) is very convenient to improve the efficiency of MAC, by mixing higher/lower bits, double clock rate, and DSP cascading. 
I cannot guarantee the performance and efficiency, when immigrating the HiPU to other vendor's FPGA.
